#!/usr/bin/env python3
"""Assembles an inherited level .tscn from a template level plus a JSON spec.

The spec (see tools/levels/README.md "Spec format"; a full example is
generated by tools/levels/examples/double_level.py) declares cell sources,
pit quads, exit/hazard/litter placement and the VoxelGI volume. The assembler
copies the template's structure (lighting, spawner, boundary, wiring),
swaps in new GridMap data + navmesh, inserts the new nodes, and recomputes
every root `index` so the override positions stay consistent.

GridMap `data` arrays are NEVER hand-written: pack_cells.gd produces them and
this tool splices the engine-serialized arrays verbatim.

Usage:
    python tools/levels/assemble_level.py --spec tools/levels/out/l4proof/spec.json
    python tools/levels/assemble_level.py --spec path/to/spec.json --out Levels/level_5.tscn
"""
from __future__ import annotations

import argparse
import json
import random
import re
import sys

TEMPLATE_SCENE = "Levels/level_template.tscn"


def parse_nodes(text: str) -> list[dict]:
    """Splits a .tscn into node blocks: {name, parent, index, text}.

    Node headers carry attributes in varying order (type=/instance= may sit
    between name= and parent=), so each attribute is matched independently.
    """
    nodes: list[dict] = []
    matches = list(re.finditer(r'^\[node name="([^"]+)"([^\n]*)\n', text, re.M))
    for i, m in enumerate(matches):
        header = m.group(0)
        pm = re.search(r'parent="([^"]*)"', header)
        im = re.search(r'index="(\d+)"', header)
        tm = re.search(r'type="([^"]*)"', header)
        end = matches[i + 1].start() if i + 1 < len(matches) else len(text)
        # Trim trailing blank lines but keep one newline.
        block = text[m.start():end].rstrip("\n") + "\n"
        nodes.append({"name": m.group(1), "parent": pm.group(1) if pm else "",
                      "index": int(im.group(1)) if im else None,
                      "type": tm.group(1) if tm else "",
                      "text": block})
    return nodes


def root_order(template_text: str) -> list[str]:
    """Root children names of the level template, in file order."""
    return [n["name"] for n in parse_nodes(template_text) if n["parent"] == "."]


def set_attr(block: str, attr: str, value: str) -> str:
    """Sets (or adds) a header attr like index=/unique_id= on a node block."""
    if re.search(rf' {attr}="[^"]*"', block):
        return re.sub(rf' {attr}="[^"]*"', f' {attr}="{value}"', block, count=1)
    if re.search(rf" {attr}=\d+", block):
        return re.sub(rf" {attr}=\d+", f" {attr}={value}", block, count=1)
    first_nl = block.index("\n")
    return block[:first_nl] + f' {attr}="{value}"' + block[first_nl:]


def set_transform_origin(block: str, x: float, y: float, z: float) -> str:
    """Rewrites a node's transform origin, preserving its basis."""
    m = re.search(r"transform = Transform3D\(([^)]+)\)", block)
    assert m, f"no transform in block:\n{block[:200]}"
    nums = [float(v) for v in m.group(1).split(",")]
    assert len(nums) == 12
    nums[9], nums[10], nums[11] = x, y, z
    return block.replace(m.group(0),
                         "transform = Transform3D(%s)" % ", ".join("%g" % v for v in nums))


def transform_origin(block: str) -> tuple[float, float, float]:
    """Reads a node's transform origin."""
    m = re.search(r"transform = Transform3D\(([^)]+)\)", block)
    assert m
    nums = [float(v) for v in m.group(1).split(",")]
    return nums[9], nums[10], nums[11]


def cells_after(text: str, marker: str) -> str:
    """Extracts the first cells array following a node marker."""
    i = text.index(marker)
    m = re.search(r'"cells": PackedInt32Array\(([^)]*)\)', text[i:])
    assert m, f"no cells after {marker}"
    return m.group(1)


def replace_cells_after(text: str, marker: str, arr: str) -> str:
    """Replaces the first cells array following a node marker."""
    i = text.index(marker)
    m = re.search(r'"cells": PackedInt32Array\([^)]*\)', text[i:])
    assert m, f"no cells after {marker}"
    return text[:i + m.start()] + f'"cells": PackedInt32Array({arr})' + text[i + m.end():]


def random_uid(rng: random.Random) -> str:
    """Generates a Godot scene uid."""
    alphabet = "abcdefghijklmnopqrstuvwxyz0123456789"
    return "uid://" + "".join(rng.choice(alphabet) for _ in range(13))


def fresh_node_id(used: set[str], rng: random.Random) -> int:
    """Generates a unique_id not present in the scene."""
    while True:
        u = rng.randint(100000000, 2147483647)
        if str(u) not in used:
            used.add(str(u))
            return u


def main() -> int:
    ap = argparse.ArgumentParser(description="Assemble an inherited level scene.")
    ap.add_argument("--spec", required=True)
    ap.add_argument("--out", default="")
    args = ap.parse_args()
    with open(args.spec) as f:
        spec: dict = json.load(f)
    rng = random.Random(spec.get("seed", 20260914))

    base_text = open(spec["template"]).read()
    out = base_text

    # --- strip template dressing the new layout does not reuse ---
    drop: set[str] = set()
    if spec.get("strip_litter"):
        drop |= {n["name"] for n in parse_nodes(base_text)
                 if n["parent"] == "NavigationRegion3D/Litter"}
    if spec.get("strip_hazards"):
        drop |= {n["name"] for n in parse_nodes(base_text)
                 if n["parent"] == "." and (n["name"].startswith("SpikesHazard")
                                           or n["name"].startswith("FireTrap"))}
    if spec.get("strip_pits"):
        drop |= {n["name"] for n in parse_nodes(base_text)
                 if n["parent"] == "." and n["name"].startswith("Pit")
                 and n["type"] == "MeshInstance3D"}
    for n in parse_nodes(base_text):
        if n["name"] in drop:
            out = out.replace(n["text"], "")
    if drop:
        print(f"stripped template nodes: {sorted(drop)}")

    # --- scene uid + root name ---
    new_uid = spec.get("uid") or random_uid(rng)
    out = re.sub(r'\[gd_scene format=3 uid="[^"]+"\]',
                 f'[gd_scene format=3 uid="{new_uid}"]', out, count=1)
    out = re.sub(r'(\[node name=")[^"]+(" unique_id=1079320019 instance=)',
                 rf"\g<1>{spec['root_name']}\g<2>", out, count=1)

    # --- GridMap cells (engine-serialized arrays spliced verbatim) ---
    packed = open(spec["packed_cells"]).read()
    floor_arr = cells_after(packed, '[node name="Floormap"')
    wall_arr = cells_after(packed, '[node name="Wallmap"')
    out = replace_cells_after(out, '[node name="Floormap"', floor_arr)
    out = replace_cells_after(out, '[node name="Wallmap"', wall_arr)

    # --- navmesh block ---
    old_nav = re.search(r'navigation_mesh = SubResource\("([^"]+)"\)', out)
    assert old_nav, "no navigation_mesh reference in template"
    old_nav_id = old_nav.group(1)
    snippet = open(spec["navmesh_snippet"]).read()
    # Greedy polygons match: the snippet ends with the closing "]", so this
    # spans every polygon (polygons themselves contain "]" characters).
    m = re.search(r"(vertices = PackedVector3Array\(.*?\))\n(polygons = \[.*\])(\n.*)?$",
                  snippet.strip(), re.S)
    assert m, "navmesh snippet parse failed"
    tail = m.group(3) or "\ngeometry_parsed_geometry_type = 1\nregion_min_size = 6.0"
    new_nav_id = spec["navmesh_id"]
    new_nav = (f'[sub_resource type="NavigationMesh" id="{new_nav_id}"]\n'
               + m.group(1) + "\n" + m.group(2) + tail)
    out = re.sub(r'\[sub_resource type="NavigationMesh" id="%s"\].*?region_min_size = 6\.0'
                 % re.escape(old_nav_id), new_nav, out, count=1, flags=re.S)
    out = out.replace(f'navigation_mesh = SubResource("{old_nav_id}")',
                      f'navigation_mesh = SubResource("{new_nav_id}")')

    # --- node bookkeeping: full root order, then reindex ---
    template_text = open(TEMPLATE_SCENE).read()
    order = root_order(template_text)
    base_nodes = [n for n in parse_nodes(base_text)
                  if n["parent"] == "." and n["name"] not in drop]
    for n in base_nodes:  # replay base overrides at their stated positions
        if n["name"] in order:
            order.remove(n["name"])
        idx = n["index"] if n["index"] is not None else len(order)
        order.insert(min(idx, len(order)), n["name"])
    last_pit = max(i for i, n in enumerate(order) if n.startswith("Pit"))
    for pit in spec.get("extra_pits", []):
        last_pit += 1
        order.insert(last_pit, pit["name"])
    for haz in spec.get("extra_hazards", []):
        order.append(haz["name"])
    if spec.get("player") is not None and "Player" not in [n["name"] for n in base_nodes]:
        order.insert(order.index("Pit"), "Player")  # template slot, before pits
    index_of = {name: i for i, name in enumerate(order)}

    used_ids = set(re.findall(r"unique_id=(\d+)", out))
    blocks: dict[str, str] = {}  # newly built node blocks, keyed by name

    def clone_pattern(pattern_name: str, new_name: str, x: float, y: float,
                      z: float) -> str:
        src = next(n for n in parse_nodes(base_text)
                   if n["name"] == pattern_name and n["parent"] in (".", "NavigationRegion3D/Litter"))
        block = src["text"]
        block = re.sub(r'\[node name="[^"]+"', f'[node name="{new_name}"', block, count=1)
        block = re.sub(r' unique_id=\d+', f' unique_id={fresh_node_id(used_ids, rng)}',
                       block, count=1)
        return set_transform_origin(block, x, y, z)

    # --- extra pits (clone the template's pit-quad pattern) ---
    pit_pattern = next(n for n in parse_nodes(base_text)
                       if n["name"] == spec.get("pit_pattern_from", "Pit2"))
    _px, py, _pz = transform_origin(pit_pattern["text"])
    for pit in spec.get("extra_pits", []):
        blocks[pit["name"]] = clone_pattern(spec.get("pit_pattern_from", "Pit2"),
                                            pit["name"], float(pit["x"]), py, float(pit["z"]))

    # --- extra hazards (clone the template's hazard pattern per kind) ---
    haz_patterns: dict[str, str] = {"spikes": spec.get("hazard_pattern_from", "SpikesHazard2")}
    haz_patterns.update(spec.get("hazard_patterns", {}))
    kind_to_scene = {"spikes": "spikes_hazard", "fire": "fire_trap"}
    haz_anchors: dict[str, list[str]] = {}
    for haz in spec.get("extra_hazards", []):
        kind = haz.get("kind", "spikes")
        assert kind in haz_patterns, f"no hazard pattern for kind {kind!r}"
        pattern_name = haz_patterns[kind]
        pattern = next(n for n in parse_nodes(base_text) if n["name"] == pattern_name)
        _hx, hy, _hz = transform_origin(pattern["text"])
        if "ext_id" in haz:
            ext_id = haz["ext_id"]
        else:
            assert kind in kind_to_scene, f"no scene known for kind {kind!r}"
            ext_id = _ext_id_for(out, kind_to_scene[kind])
        block = clone_pattern(pattern_name, haz["name"], float(haz["x"]), hy,
                              float(haz["z"]))
        old_ext = re.search(r'instance=ExtResource\("([^"]+)"\)', block)
        assert old_ext
        block = block.replace(f'instance=ExtResource("{old_ext.group(1)}")',
                              f'instance=ExtResource("{ext_id}")')
        blocks[haz["name"]] = block
        haz_anchors.setdefault(pattern_name, []).append(haz["name"])

    # --- litter copies (clone a template prop, shifted) ---
    litter_nodes = [n for n in parse_nodes(base_text)
                    if n["parent"] == "NavigationRegion3D/Litter"]
    litter_by_name = {n["name"]: n for n in litter_nodes}
    for copy in spec.get("litter_copies", []):
        assert litter_by_name, "litter_copies needs template litter (or drop strip_litter)"
        src = litter_by_name[copy["from"]]
        block = src["text"]
        block = re.sub(r'\[node name="[^"]+"', f'[node name="{copy["name"]}"', block, count=1)
        block = re.sub(r' unique_id=\d+', f' unique_id={fresh_node_id(used_ids, rng)}',
                       block, count=1)
        ox, oy, oz = transform_origin(block)
        block = set_transform_origin(block, ox + float(copy.get("dx", 0)), oy,
                                     oz + float(copy.get("dz", 0)))
        blocks[copy["name"]] = block

    # --- litter placed explicitly ({name, scene, pos, rot_y}) ---
    scene_nicknames = {"couch": "Couch", "barrel": "Barrel", "flag": "Flag"}
    for placed in spec.get("litter_placed", []):
        nick = placed["scene"]
        assert nick in scene_nicknames, f"unknown litter scene {nick!r}"
        ext_id = _ext_id_for(out, scene_nicknames[nick])
        px, py, pz = placed["pos"]
        block = (f'[node name="{placed["name"]}" parent="NavigationRegion3D/Litter" index="0" '
                 f'unique_id={fresh_node_id(used_ids, rng)} instance=ExtResource("{ext_id}")]\n'
                 f'transform = Transform3D({_yaw_basis(float(placed.get("rot_y", 0)))}, '
                 f'{px:g}, {py:g}, {pz:g})\n')
        blocks[placed["name"]] = block

    # --- splice new blocks into the file text ---
    # Litter goes right after the last litter child (or the Litter container
    # when the template's dressing was stripped).
    litter_add = [blocks[c["name"]] for c in spec.get("litter_copies", [])]
    litter_add += [blocks[p["name"]] for p in spec.get("litter_placed", [])]
    if litter_add:
        remaining_litter = [n for n in parse_nodes(out)
                            if n["parent"] == "NavigationRegion3D/Litter"]
        if remaining_litter:
            out = _insert_after_pattern(out, remaining_litter[-1]["text"].rstrip("\n"),
                                        "\n".join(litter_add))
        else:
            out = _insert_after_node(out, "Litter", "\n".join(litter_add))
    # Extra pits go right after the pattern pit; when the template's pits
    # were stripped, after the last remaining Pit node (else ExitPoint).
    if spec.get("extra_pits"):
        present = {n["name"] for n in parse_nodes(out)}
        pattern = spec.get("pit_pattern_from", "Pit2")
        if pattern in present:
            pit_anchor = pattern
        else:
            pits_left = [n["name"] for n in parse_nodes(out) if n["name"].startswith("Pit")]
            pit_anchor = pits_left[-1] if pits_left else "ExitPoint"
        out = _insert_after_node(out, pit_anchor,
                                 "\n".join(blocks[p["name"]] for p in spec["extra_pits"]))
    # Extra hazards go right after their own pattern node, or chained after
    # the pits when the template's hazards were stripped.
    present = {n["name"] for n in parse_nodes(out)}
    pit_names = [p["name"] for p in spec.get("extra_pits", [])]
    fallback = pit_names[-1] if pit_names else "ExitPoint"
    for pattern_name, names in haz_anchors.items():
        anchor = pattern_name if pattern_name in present else fallback
        out = _insert_after_node(out, anchor, "\n".join(blocks[n] for n in names))
        fallback = names[-1]

    # --- exit / player overrides ---
    ex, ey, ez = spec["exit"]
    out = _retarget_node(out, "ExitPoint", ex, ey, ez)
    if spec.get("player") is not None:
        px, py, pz = spec["player"]
        if re.search(r'^\[node name="Player" parent="\."', out, re.M):
            out = _retarget_node(out, "Player", px, py, pz)
        else:
            player_block = (f'[node name="Player" parent="." unique_id=602303743]\n'
                            f'transform = Transform3D(1, 0, 0, 0, 1, 0, 0, 0, 1, {px:g}, {py:g}, {pz:g})\n')
            pit_block = next(n for n in parse_nodes(out) if n["name"].startswith("Pit"))
            out = out.replace(pit_block["text"], player_block + "\n" + pit_block["text"])

    # --- hide inherited nodes a pit-less layout must not show ---
    # Child scenes cannot delete nodes inherited from the template chain —
    # dropping an override block only reverts to the template's version. The
    # template's "Pit" quad (MeshInstance3D) is typeless in level_2/3
    # overrides, so strip_pits leaves it behind: harmless when buried under
    # floor (Level 5), but a floating black quad over any void gap. Levels
    # with no pits set "hide_nodes": ["Pit"] to pin visible=false instead.
    for hidden in spec.get("hide_nodes", []):
        blk = next((n for n in parse_nodes(out)
                    if n["name"] == hidden and n["parent"] == "."), None)
        assert blk is not None, f"hide_nodes: no root override for {hidden!r}"
        if not re.search(r"(?m)^visible =", blk["text"]):
            out = out.replace(blk["text"], blk["text"].rstrip("\n")
                              + "\nvisible = false\n")

    # --- VoxelGI volume (+ optional baked data reference) ---
    gx, gy, gz = spec["voxelgi"]["pos"]
    gsx, gsy, gsz = spec["voxelgi"]["size"]
    gi_block = next(n for n in parse_nodes(out) if n["name"] == "VoxelGI")
    new_gi = re.sub(r"transform = Transform3D\([^)]*\)",
                    f"transform = Transform3D(1, 0, 0, 0, 1, 0, 0, 0, 1, {gx:g}, {gy:g}, {gz:g})",
                    gi_block["text"], count=1)
    new_gi = re.sub(r"size = Vector3\([^)]*\)",
                    f"size = Vector3({gsx:g}, {gsy:g}, {gsz:g})", new_gi, count=1)
    gi_data = spec.get("gi_data")
    old_gi_ext = re.search(r'\[ext_resource type="VoxelGIData"[^]]*id="([^"]+)"\]', out)
    if gi_data:
        gi_ext_id = spec.get("gi_ext_id", "4_gi")
        if old_gi_ext:
            new_gi = re.sub(r'data = ExtResource\("[^"]+"\)',
                            f'data = ExtResource("{gi_ext_id}")', new_gi)
            out = re.sub(r'\[ext_resource type="VoxelGIData"[^\]]*\]',
                         f'[ext_resource type="VoxelGIData" path="{gi_data}" id="{gi_ext_id}"]',
                         out, count=1)
        else:
            new_gi = new_gi.rstrip("\n") + f'\ndata = ExtResource("{gi_ext_id}")\n'
            m2 = list(re.finditer(r"^\[ext_resource[^\n]*\n", out, re.M))[-1]
            out = out[:m2.end()] + (f'[ext_resource type="VoxelGIData" path="{gi_data}" '
                                    f'id="{gi_ext_id}"]\n') + out[m2.end():]
    else:
        new_gi = re.sub(r"\ndata = ExtResource\(\"[^\"]+\"\)", "", new_gi)
        if old_gi_ext:
            out = re.sub(r"^\[ext_resource type=\"VoxelGIData\"[^\n]*\n", "", out,
                         count=1, flags=re.M)
    out = out.replace(gi_block["text"], new_gi)

    # --- reindex every root override to its recomputed position ---
    for n in parse_nodes(out):
        if n["parent"] == "." and n["name"] in index_of:
            if n["index"] is not None:
                new_block = re.sub(r' index="\d+"', f' index="{index_of[n["name"]]}"',
                                   n["text"], count=1)
            else:
                new_block = set_attr(n["text"], "index", str(index_of[n["name"]]))
            out = out.replace(n["text"], new_block)
    litter_new = [c["name"] for c in spec.get("litter_copies", [])]
    litter_new += [p["name"] for p in spec.get("litter_placed", [])]
    remaining_idx = [x["index"] for x in parse_nodes(out)
                     if x["parent"] == "NavigationRegion3D/Litter" and x["index"] is not None
                     and x["name"] not in litter_new]
    base_idx = max(remaining_idx) if remaining_idx else -1
    for pos, name in enumerate(litter_new, start=base_idx + 1):
        n = next(x for x in parse_nodes(out) if x["name"] == name)
        out = out.replace(n["text"], re.sub(r' index="\d+"', f' index="{pos}"',
                                            n["text"], count=1))

    out_path = args.out or spec["out"]
    with open(out_path, "w") as f:
        f.write(out)
    print(f"assembled {out_path} ({len(out)} bytes), "
          f"floor+pits+hazards+litter: +{len(spec.get('extra_pits', []))}/"
          f"+{len(spec.get('extra_hazards', []))}/+{len(spec.get('litter_copies', []))}")
    return 0


def _ext_id_for(text: str, scene_substring: str) -> str:
    """Finds an ExtResource id by filename substring (e.g. "Couch" -> "3_abc")."""
    for m in re.finditer(r'\[ext_resource[^]]*path="([^"]+)"[^]]*id="([^"]+)"\]', text):
        if scene_substring.lower() in m.group(1).lower():
            return m.group(2)
    raise AssertionError(f"no ExtResource matching {scene_substring!r} (pick a template containing it)")


def _snap_g(v: float) -> str:
    """Snaps near-integers/zeros so generated transforms print cleanly."""
    if abs(v) < 0.0000005:
        return "0"
    if abs(v - round(v)) < 0.0000005:
        return str(int(round(v)))
    return "%g" % v


def _yaw_basis(rot_y_deg: float) -> str:
    """Builds a Transform3D basis triple for a yaw rotation (degrees)."""
    import math
    r = math.radians(rot_y_deg)
    c = math.cos(r)
    s = math.sin(r)
    return "%s, 0, %s, 0, 1, 0, %s, 0, %s" % (_snap_g(c), _snap_g(-s), _snap_g(s), _snap_g(c))


def _insert_after_pattern(text: str, pattern: str, addition: str) -> str:
    """Inserts `addition` right after the first occurrence of `pattern`.

    `pattern` is matched rstripped (no trailing newline); the insertion is
    wrapped so exactly one blank line separates it from its neighbours,
    matching the surrounding .tscn style.
    """
    if not addition.strip():
        return text
    i = text.index(pattern)
    rest = text[i + len(pattern):].lstrip("\n")
    return text[:i + len(pattern)] + "\n\n" + addition.strip("\n") + "\n\n" + rest


def _insert_after_node(text: str, node_name: str, addition: str) -> str:
    """Inserts `addition` right after a node's full block."""
    if not addition.strip():
        return text
    nodes = [n for n in parse_nodes(text) if n["name"] == node_name]
    assert nodes, f"anchor node {node_name} not found"
    anchor = nodes[-1]["text"]
    i = text.index(anchor)
    return text[:i + len(anchor)] + "\n" + addition + text[i + len(anchor):]


def _retarget_node(text: str, node_name: str, x: float, y: float, z: float) -> str:
    """Rewrites a node's transform origin in place."""
    nodes = [n for n in parse_nodes(text) if n["name"] == node_name]
    assert nodes, f"node {node_name} not found"
    block = set_transform_origin(nodes[0]["text"], x, y, z)
    return text.replace(nodes[0]["text"], block)


if __name__ == "__main__":
    sys.exit(main())

